#!/bin/sh

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

lnk=$(readlink /usr/lib/locale)
tgt=/media/internal/.widk/usr/lib/locale

if [ "x$lnk" == "x$tgt" ]
then
	rm -f /usr/lib/locale
fi
	
rm -rf $tgt

